-- MySQL Script generated by MySQL Workbench
-- Sat Oct 10 15:44:59 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SIDECOM
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SIDECOM
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SIDECOM` DEFAULT CHARACTER SET utf8 ;
USE `SIDECOM` ;

-- -----------------------------------------------------
-- Table `SIDECOM`.`provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SIDECOM`.`provincia` (
  `provincia_id` INT NOT NULL AUTO_INCREMENT,
  `provincia_nombre` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`provincia_id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `Provincia_Id_UNIQUE` ON `SIDECOM`.`provincia` (`provincia_id` ASC) ;


-- -----------------------------------------------------
-- Table `SIDECOM`.`ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SIDECOM`.`ciudad` (
  `ciudad_id` INT NOT NULL AUTO_INCREMENT,
  `ciudad_nombre` VARCHAR(70) NOT NULL,
  `ciudad_codigo_postal` INT NOT NULL,
  `provincia_id` INT NOT NULL,
  PRIMARY KEY (`ciudad_id`),
  CONSTRAINT `provincia_id`
    FOREIGN KEY (`provincia_id`)
    REFERENCES `SIDECOM`.`provincia` (`provincia_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `Ciudad_Id_UNIQUE` ON `SIDECOM`.`ciudad` (`ciudad_id` ASC) ;

CREATE INDEX `provincia_id_idx` ON `SIDECOM`.`ciudad` (`provincia_id` ASC) ;


-- -----------------------------------------------------
-- Table `SIDECOM`.`barrio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SIDECOM`.`barrio` (
  `barrio_id` INT NOT NULL AUTO_INCREMENT,
  `nombre_barrio` VARCHAR(70) NOT NULL,
  `ciudad_id` INT NOT NULL,
  PRIMARY KEY (`barrio_id`),
  CONSTRAINT `fk_barrio_ciudad1`
    FOREIGN KEY (`ciudad_id`)
    REFERENCES `SIDECOM`.`ciudad` (`ciudad_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `Barrio_Id_UNIQUE` ON `SIDECOM`.`barrio` (`barrio_id` ASC) ;

CREATE INDEX `fk_barrio_ciudad1_idx` ON `SIDECOM`.`barrio` (`ciudad_id` ASC) ;


-- -----------------------------------------------------
-- Table `SIDECOM`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SIDECOM`.`cliente` (
  `cliente_documento` BIGINT NOT NULL,
  `cliente_nombre` VARCHAR(30) NOT NULL,
  `cliente_apellido` VARCHAR(30) NULL,
  `cliente_nacimiento` DATE NULL,
  `cliente_domicilio` VARCHAR(70) NOT NULL,
  `cliente_manzana` INT NULL,
  `cliente_monoblock` INT NULL,
  `cliente_departamento` VARCHAR(10) NULL,
  `cliente_celular` BIGINT NOT NULL,
  `cliente_telefono` BIGINT NULL,
  `cliente_correo` VARCHAR(100) NULL,
  `cliente_numero_abonado` INT NOT NULL,
  `cliente_fecha_alta` DATE NOT NULL,
  `cliente_estado` TINYINT NOT NULL,
  `barrio_id` INT NULL,
  `ciudad_id` INT NOT NULL,
  PRIMARY KEY (`cliente_documento`),
  CONSTRAINT `barrio_id`
    FOREIGN KEY (`barrio_id`)
    REFERENCES `SIDECOM`.`barrio` (`barrio_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ciudad_id`
    FOREIGN KEY (`ciudad_id`)
    REFERENCES `SIDECOM`.`ciudad` (`ciudad_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `cliente_documento_UNIQUE` ON `SIDECOM`.`cliente` (`cliente_documento` ASC) ;

CREATE INDEX `barrio_id_idx` ON `SIDECOM`.`cliente` (`barrio_id` ASC) ;

CREATE INDEX `ciudad_id_idx` ON `SIDECOM`.`cliente` (`ciudad_id` ASC) ;


-- -----------------------------------------------------
-- Table `SIDECOM`.`tipo_moneda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SIDECOM`.`tipo_moneda` (
  `tipo_moneda_id` INT NOT NULL AUTO_INCREMENT,
  `tipo_moneda_nombre` VARCHAR(50) NOT NULL,
  `tipo_moneda_codigo` VARCHAR(3) NOT NULL COMMENT 'Segun la norma ISO 4217',
  PRIMARY KEY (`tipo_moneda_id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `TipoMoneda_Id_UNIQUE` ON `SIDECOM`.`tipo_moneda` (`tipo_moneda_id` ASC) ;


-- -----------------------------------------------------
-- Table `SIDECOM`.`tipo_servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SIDECOM`.`tipo_servicio` (
  `tipo_servicio_id` INT NOT NULL AUTO_INCREMENT,
  `tipo_servicio_nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`tipo_servicio_id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `TipoServicio_Id_UNIQUE` ON `SIDECOM`.`tipo_servicio` (`tipo_servicio_id` ASC) ;


-- -----------------------------------------------------
-- Table `SIDECOM`.`servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SIDECOM`.`servicio` (
  `servicio_id` INT NOT NULL AUTO_INCREMENT,
  `servicio_nombre` VARCHAR(40) NOT NULL,
  `servicio_detalle` VARCHAR(60) NOT NULL,
  `servicio_subida` INT NOT NULL,
  `servicio_monto` DECIMAL(11,2) NOT NULL,
  `servicio_iva` DECIMAL(2,1) NOT NULL,
  `tipo_moneda_id` INT NOT NULL,
  `tipo_servicio_id` INT NOT NULL,
  `servicio_bajada` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`servicio_id`),
  CONSTRAINT `tipo_moneda_id`
    FOREIGN KEY (`tipo_moneda_id`)
    REFERENCES `SIDECOM`.`tipo_moneda` (`tipo_moneda_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `tipo_servicio_id`
    FOREIGN KEY (`tipo_servicio_id`)
    REFERENCES `SIDECOM`.`tipo_servicio` (`tipo_servicio_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `Servicio_Id_UNIQUE` ON `SIDECOM`.`servicio` (`servicio_id` ASC) ;

CREATE INDEX `tipo_moneda_id_idx` ON `SIDECOM`.`servicio` (`tipo_moneda_id` ASC) ;

CREATE INDEX `tipo_servicio_id_idx` ON `SIDECOM`.`servicio` (`tipo_servicio_id` ASC) ;


-- -----------------------------------------------------
-- Table `SIDECOM`.`adhesion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SIDECOM`.`adhesion` (
  `cliente_documento` BIGINT NOT NULL,
  `servicio_id` INT NOT NULL,
  `adhesion_estado` TINYINT NOT NULL COMMENT '0 eliminado\n1 activa\n',
  PRIMARY KEY (`cliente_documento`, `servicio_id`),
  CONSTRAINT `cliente_documento`
    FOREIGN KEY (`cliente_documento`)
    REFERENCES `SIDECOM`.`cliente` (`cliente_documento`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `servicio`
    FOREIGN KEY (`servicio_id`)
    REFERENCES `SIDECOM`.`servicio` (`servicio_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `cliente_documento_idx` ON `SIDECOM`.`adhesion` (`cliente_documento` ASC) ;

CREATE INDEX `servicio_idx` ON `SIDECOM`.`adhesion` (`servicio_id` ASC) ;


-- -----------------------------------------------------
-- Table `SIDECOM`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SIDECOM`.`usuario` (
  `usuario_id` INT NOT NULL AUTO_INCREMENT,
  `usuario_documento` BIGINT NOT NULL,
  `usuario_nombre` VARCHAR(30) NOT NULL,
  `usuario_apellido` VARCHAR(30) NOT NULL,
  `usuario_nacimiento` DATE NULL,
  `usuario_domicilio` VARCHAR(50) NULL,
  `usuario_telefono` BIGINT NULL,
  `usuario_correo` VARCHAR(100) NULL,
  `usuario_fecha_ingreso` DATE NULL,
  `usuario_salario` DECIMAL(10,2) NULL,
  `usuario_usuario` VARCHAR(45) NOT NULL,
  `usuario_password` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `usuario_estado` TINYINT NOT NULL COMMENT '0 bloqueado\n1 habilitado\n2 espera de aprobacion\n3 no es empleado',
  `ciudad_id` INT NOT NULL,
  PRIMARY KEY (`usuario_id`),
  CONSTRAINT `fk_usuario_ciudad1`
    FOREIGN KEY (`ciudad_id`)
    REFERENCES `SIDECOM`.`ciudad` (`ciudad_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `Usuario_Id_UNIQUE` ON `SIDECOM`.`usuario` (`usuario_id` ASC) ;

CREATE UNIQUE INDEX `usuario_documento_UNIQUE` ON `SIDECOM`.`usuario` (`usuario_documento` ASC) ;

CREATE INDEX `fk_usuario_ciudad1_idx` ON `SIDECOM`.`usuario` (`ciudad_id` ASC) ;

CREATE UNIQUE INDEX `usuario_usuario_UNIQUE` ON `SIDECOM`.`usuario` (`usuario_usuario` ASC) ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
